# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.CharField(default='', max_length=128)),
                ('college_name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.CharField(default='', max_length=128)),
                ('created', models.CharField(default='', max_length=128)),
                ('updated', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.CharField(default='', max_length=128)),
                ('subject_name', models.CharField(default='', max_length=128)),
                ('subject_description', models.TextField(blank=True)),
                ('subject_deadline', models.CharField(default='', max_length=128)),
                ('gre_cut_off_verbal', models.CharField(default='130', max_length=24)),
                ('gre_cut_off_quant', models.CharField(default='130', max_length=24)),
                ('ug_gpa', models.CharField(default='3', max_length=24)),
                ('work_exp', models.CharField(default='1', max_length=24)),
                ('created', models.CharField(default='', max_length=128)),
                ('updated', models.CharField(default='', max_length=128)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadline.College')),
            ],
        ),
    ]
