# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='deadline_type',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
