# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.CharField(default=b'', max_length=128)),
                ('updated', models.CharField(default=b'', max_length=128)),
                ('created', models.CharField(default=b'', max_length=128)),
                ('access_token', models.CharField(default=b'', max_length=128)),
                ('imei_number', models.CharField(default=b'', max_length=128)),
            ],
        ),
    ]
