# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 07:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='definition',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='vocab',
            name='examples',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='vocab',
            name='frequency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vocab',
            name='synonyms',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
